"""
Crée 4 références exemplaires pour bootstrap les nouvelles catégories Phase 2.

  Glace nue :
    - REF-GNRS-034 : Glace brute ronde saphir Ø34mm — poli optique
    - REF-GNRM-036 : Glace brute ronde minérale Ø36mm — poli fin

  Céramique :
    - REF-CEBA-010 : Bague alumine 99% Ø10mm — rectification + polissage miroir
    - REF-CECZ-005 : Cale zircone Y-TZP 5×5×1mm — rectification diamant
"""

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
CATEGORIES = ROOT / "categories"


# ═══════════════════════════════════════════════════════════════════════════════
# RÉFÉRENCES GLACE NUE
# ═══════════════════════════════════════════════════════════════════════════════

GLACE_NUE_REFS = [
    {
        "code": "REF-GNRS-034",
        "designation": "Glace brute ronde saphir Ø34mm — poli optique",
        "type_produit": "glace_brute_ronde",
        "matiere": "saphir_brut",
        "traitements": ["poli_optique", "chanfrein", "rodage_zone_joint"],
        "dimensions": {"diametre_mm": 34.0, "tolerance_diametre_mm": 0.05,
                       "epaisseur_mm": 1.5, "tolerance_epaisseur_mm": 0.03},
        "amdec_produit": [
            {"no": "01", "famille": "geometrique",
             "fonction_exigence": "Conformité dimensionnelle", "caracteristique_critique": "Diamètre",
             "mode_defaillance": "Diamètre hors tolérance",
             "effets_defaillance": "Impossibilité montage boîtier client",
             "G": 9, "causes_defaillance": "Dérive rectif diamant, usure outil",
             "O": 2, "controles_existants": "Pied à coulisse digital 100%",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "SPC diamètre + remplacement outil tous les 500 pcs",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "02", "famille": "geometrique",
             "fonction_exigence": "Conformité épaisseur", "caracteristique_critique": "Épaisseur",
             "mode_defaillance": "Épaisseur hors tolérance",
             "effets_defaillance": "Saillie ou encastrement incorrect",
             "G": 7, "causes_defaillance": "Polissage trop appuyé / hétérogène",
             "O": 3, "controles_existants": "Micromètre digital 100%",
             "D": 2, "classe_criticite": "Surveillance",
             "actions_correctives": "Plan SPC épaisseur, calibration micromètre mensuelle",
             "responsable": "BT Qualité", "delai": "J+30"},
            {"no": "03", "famille": "geometrique",
             "fonction_exigence": "Planéité", "caracteristique_critique": "Planéité globale",
             "mode_defaillance": "Planéité hors tolérance (> 0.01mm)",
             "effets_defaillance": "Contrainte montage, refus client",
             "G": 8, "causes_defaillance": "Bridage incorrect lors polissage",
             "O": 3, "controles_existants": "Mesure marbre + comparateur",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Bridage par 3 points, contrôle planéité 100%",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "04", "famille": "surface",
             "fonction_exigence": "Qualité polissage optique", "caracteristique_critique": "Rugosité Ra",
             "mode_defaillance": "Rugosité Ra > 5nm (poli optique non atteint)",
             "effets_defaillance": "Perte transmission optique en aval",
             "G": 7, "causes_defaillance": "Pâte polissage usée, durée polissage insuffisante",
             "O": 4, "controles_existants": "Rugosimètre AFM 1/lot",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Renouvellement pâte tous les 100 pcs, durée polissage normalisée",
             "responsable": "Resp. Process", "delai": "J+15"},
            {"no": "05", "famille": "surface",
             "fonction_exigence": "Aspect surface", "caracteristique_critique": "Absence de rayures",
             "mode_defaillance": "Rayures visibles post-polissage",
             "effets_defaillance": "Refus qualité, rebut pièce",
             "G": 7, "causes_defaillance": "Particule abrasive en suspension dans pâte",
             "O": 4, "controles_existants": "Inspection x50 sous éclairage rasant 100%",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "Filtration pâte, salle propre dédiée polissage",
             "responsable": "Resp. Process", "delai": "J+15"},
            {"no": "06", "famille": "integrite",
             "fonction_exigence": "Intégrité bordure", "caracteristique_critique": "Absence d'éclats",
             "mode_defaillance": "Éclats / microfissures bordure",
             "effets_defaillance": "Risque blessure, étanchéité compromise en aval",
             "G": 8, "causes_defaillance": "Sciage diamant trop agressif, choc manutention",
             "O": 3, "controles_existants": "Inspection x50 bordure 100%",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "Vitesse sciage réduite + chanfrein systématique",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "07", "famille": "integrite",
             "fonction_exigence": "Zone joint", "caracteristique_critique": "Rugosité zone joint",
             "mode_defaillance": "Rodage zone joint insuffisant",
             "effets_defaillance": "Fuite étanchéité montre en aval",
             "G": 9, "causes_defaillance": "Outil rodage usé",
             "O": 3, "controles_existants": "Rugosimètre zone annulaire 100%",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Plan SPC rugosité zone joint, remplacement outil 500 pcs",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "08", "famille": "tracabilite",
             "fonction_exigence": "Identification", "caracteristique_critique": "Référence + lot",
             "mode_defaillance": "Confusion référence",
             "effets_defaillance": "Mauvais produit livré pour traitement aval",
             "G": 8, "causes_defaillance": "Étiquetage défaillant entre opérations",
             "O": 2, "controles_existants": "Scan code-barres systématique",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "Kanban physique entre opérations",
             "responsable": "Resp. Qualité", "delai": "J+7"},
        ],
        "amdec_process": [
            {"no": "01", "operation_process": "OP-10 Sciage diamant", "etape_poste": "Scie diamant",
             "mode_defaillance": "Éclats bordure lors sciage",
             "effets_produit": "Microfissures invisibles, casse en aval",
             "G": 8, "causes_process": "Vitesse trop élevée, pression excessive",
             "O": 4, "controles_process": "Inspection x50 100% bordure post-sciage",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Réduire vitesse rotation, augmenter arrosage",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Vitesse rotation lame", "valeur_cible": "1500 RPM ± 100"},
            {"no": "02", "operation_process": "OP-20 Rectification", "etape_poste": "Rectifieuse plane",
             "mode_defaillance": "Cote diamètre hors tolérance",
             "effets_produit": "Pièce hors spec, rebut",
             "G": 9, "causes_process": "Usure meule diamant, dérive thermique",
             "O": 3, "controles_process": "Mesure pied à coulisse 100% post-rectif",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "Dressage meule toutes les 200 pcs, contrôle thermique",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Avance meule", "valeur_cible": "0.02mm/pass"},
            {"no": "03", "operation_process": "OP-30 Polissage optique", "etape_poste": "Polisseuse",
             "mode_defaillance": "Ra > 5nm",
             "effets_produit": "Aspect non-conforme, transmission insuffisante en aval",
             "G": 7, "causes_process": "Pâte usée, durée trop courte",
             "O": 4, "controles_process": "Rugosimètre AFM 1/lot",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Renouvellement pâte 100 pcs, durée standardisée",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Durée polissage", "valeur_cible": "45 min ± 5"},
            {"no": "04", "operation_process": "OP-40 Rodage zone joint", "etape_poste": "Roueuse",
             "mode_defaillance": "Rugosité zone joint insuffisante",
             "effets_produit": "Fuite étanchéité en aval",
             "G": 9, "causes_process": "Outil rodage usé",
             "O": 3, "controles_process": "Rugosimètre zone annulaire 100%",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Remplacement outil 500 pcs, contrôle systématique",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Pression rodage", "valeur_cible": "2 bars ± 0.2"},
            {"no": "05", "operation_process": "OP-90 Contrôle final", "etape_poste": "Table qualité",
             "mode_defaillance": "Défaut non détecté",
             "effets_produit": "Livraison pièce non-conforme",
             "G": 9, "causes_process": "Fatigue opérateur, critères ambigus",
             "O": 3, "controles_process": "Inspection 100% selon gamme",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Référentiels visuels + rotation 2h max",
             "responsable": "Resp. Qualité", "delai": "J+15",
             "parametre_cle": "Tous critères", "valeur_cible": "Conforme plan"},
        ],
        "gamme": [
            {"no_op": "10", "designation": "Réception matière brute",
             "description_detaillee": "Contrôle visuel et dimensionnel des plaquettes saphir entrantes",
             "poste_machine": "Zone réception", "outillage_fixture": "Pied à coulisse digital",
             "parametre_1": "Épaisseur plaquette", "valeur_1": "1.8mm ± 0.05",
             "parametre_2": "Aspect", "valeur_2": "Sans défaut visible",
             "parametre_3": "—", "temps_min": 10,
             "point_controle": "Cotes + aspect", "moyen_controle": "Pied à coulisse + visuel",
             "frequence": "100%", "critere_acceptation": "Conforme certificat fournisseur",
             "ref_dit": "DIT-010", "ref_infor": "OP-10"},
            {"no_op": "20", "designation": "Sciage diamant",
             "description_detaillee": "Découpe ronde Ø34mm depuis plaquette brute saphir",
             "poste_machine": "Scie diamant", "outillage_fixture": "Lame diamant 150mm",
             "parametre_1": "Vitesse rotation", "valeur_1": "1500 RPM ± 100",
             "parametre_2": "Avance", "valeur_2": "0.5 mm/min",
             "parametre_3": "Arrosage", "temps_min": 15,
             "point_controle": "Bordure", "moyen_controle": "Inspection x50",
             "frequence": "100%", "critere_acceptation": "0 éclat > 0.05mm",
             "ref_dit": "DIT-020", "ref_infor": "OP-20"},
            {"no_op": "30", "designation": "Rectification diamètre",
             "description_detaillee": "Mise à la cote finale diamètre Ø34mm ± 0.05",
             "poste_machine": "Rectifieuse cylindrique", "outillage_fixture": "Meule diamant",
             "parametre_1": "Diamètre cible", "valeur_1": "Ø34.00 ± 0.05",
             "parametre_2": "Avance", "valeur_2": "0.02mm/pass",
             "parametre_3": "—", "temps_min": 20,
             "point_controle": "Diamètre", "moyen_controle": "Pied à coulisse digital",
             "frequence": "100%", "critere_acceptation": "Ø34 ± 0.05",
             "ref_dit": "DIT-030", "ref_infor": "OP-30"},
            {"no_op": "40", "designation": "Polissage optique 2 faces",
             "description_detaillee": "Polissage optique double face pour Ra ≤ 5nm",
             "poste_machine": "Polisseuse double face", "outillage_fixture": "Pâte diamant 1µm",
             "parametre_1": "Durée polissage", "valeur_1": "45 min ± 5",
             "parametre_2": "Pression", "valeur_2": "1.5 bar",
             "parametre_3": "Vitesse plateau", "temps_min": 50,
             "point_controle": "Rugosité Ra", "moyen_controle": "Rugosimètre AFM",
             "frequence": "1/lot", "critere_acceptation": "Ra ≤ 5nm sur 5 zones",
             "ref_dit": "DIT-040", "ref_infor": "OP-40"},
            {"no_op": "50", "designation": "Chanfrein bordure",
             "description_detaillee": "Chanfrein 0.1×45° périphérie pour éviter éclats",
             "poste_machine": "Chanfreineuse", "outillage_fixture": "Outil diamant",
             "parametre_1": "Angle chanfrein", "valeur_1": "45°",
             "parametre_2": "Profondeur", "valeur_2": "0.1mm",
             "parametre_3": "—", "temps_min": 10,
             "point_controle": "Chanfrein", "moyen_controle": "Projecteur de profil",
             "frequence": "100%", "critere_acceptation": "Conforme spec",
             "ref_dit": "DIT-050", "ref_infor": "OP-50"},
            {"no_op": "60", "designation": "Rodage zone joint",
             "description_detaillee": "Rodage couronne périphérique zone d'appui joint étanchéité",
             "poste_machine": "Roueuse", "outillage_fixture": "Outil rodage spécifique",
             "parametre_1": "Pression", "valeur_1": "2 bars ± 0.2",
             "parametre_2": "Durée", "valeur_2": "5 min",
             "parametre_3": "—", "temps_min": 8,
             "point_controle": "Rugosité zone joint", "moyen_controle": "Rugosimètre",
             "frequence": "100%", "critere_acceptation": "Ra ≤ 0.4µm zone annulaire",
             "ref_dit": "DIT-060", "ref_infor": "OP-60"},
            {"no_op": "70", "designation": "Contrôle dimensionnel final",
             "description_detaillee": "Contrôle complet diamètre + épaisseur + planéité",
             "poste_machine": "Métrologie", "outillage_fixture": "Pied à coulisse + micromètre + marbre",
             "parametre_1": "Diamètre", "valeur_1": "Ø34.00 ± 0.05",
             "parametre_2": "Épaisseur", "valeur_2": "1.5 ± 0.03",
             "parametre_3": "Planéité", "temps_min": 15,
             "point_controle": "Toutes cotes", "moyen_controle": "Métrologie complète",
             "frequence": "100%", "critere_acceptation": "Toutes cotes conformes",
             "ref_dit": "DIT-070", "ref_infor": "OP-70"},
            {"no_op": "80", "designation": "Conditionnement",
             "description_detaillee": "Emballage individuel film ESD pour expédition vers traitements",
             "poste_machine": "Poste emballage", "outillage_fixture": "Film ESD",
             "parametre_1": "Type emballage", "valeur_1": "ESD anti-rayure",
             "parametre_2": "Étiquette", "valeur_2": "REF + LOT + DATE",
             "parametre_3": "—", "temps_min": 8,
             "point_controle": "Étiquetage", "moyen_controle": "Vérif + scan",
             "frequence": "100%", "critere_acceptation": "Étiquetage correct",
             "ref_dit": "DIT-080", "ref_infor": "OP-80"},
        ],
    },
    {
        "code": "REF-GNRM-036",
        "designation": "Glace brute ronde minérale Ø36mm — poli fin",
        "type_produit": "glace_brute_ronde",
        "matiere": "mineral_brut",
        "traitements": ["poli_fin", "chanfrein"],
        "dimensions": {"diametre_mm": 36.0, "tolerance_diametre_mm": 0.05,
                       "epaisseur_mm": 2.0, "tolerance_epaisseur_mm": 0.03},
        "amdec_produit": [
            {"no": "01", "famille": "geometrique",
             "fonction_exigence": "Conformité dimensionnelle", "caracteristique_critique": "Diamètre",
             "mode_defaillance": "Diamètre hors tolérance",
             "effets_defaillance": "Impossibilité montage", "G": 9,
             "causes_defaillance": "Dérive rectif", "O": 2,
             "controles_existants": "Pied à coulisse digital 100%", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "SPC diamètre", "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "02", "famille": "geometrique",
             "fonction_exigence": "Conformité épaisseur", "caracteristique_critique": "Épaisseur",
             "mode_defaillance": "Épaisseur hors tolérance",
             "effets_defaillance": "Problème montage", "G": 7,
             "causes_defaillance": "Polissage hétérogène", "O": 3,
             "controles_existants": "Micromètre 100%", "D": 2,
             "classe_criticite": "Surveillance",
             "actions_correctives": "Plan SPC épaisseur", "responsable": "BT Qualité", "delai": "J+30"},
            {"no": "03", "famille": "surface",
             "fonction_exigence": "Qualité polissage fin", "caracteristique_critique": "Rugosité Ra",
             "mode_defaillance": "Ra > 50nm (poli fin non atteint)",
             "effets_defaillance": "Aspect terne", "G": 6,
             "causes_defaillance": "Polissage insuffisant", "O": 4,
             "controles_existants": "Rugosimètre 1/lot", "D": 3,
             "classe_criticite": "Surveillance",
             "actions_correctives": "Standard durée polissage",
             "responsable": "Resp. Process", "delai": "J+30"},
            {"no": "04", "famille": "surface",
             "fonction_exigence": "Aspect surface", "caracteristique_critique": "Absence rayures",
             "mode_defaillance": "Rayures visibles", "effets_defaillance": "Refus esthétique",
             "G": 7, "causes_defaillance": "Particule abrasive", "O": 4,
             "controles_existants": "Inspection x20", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Filtration pâte", "responsable": "Resp. Process", "delai": "J+15"},
            {"no": "05", "famille": "integrite",
             "fonction_exigence": "Intégrité bordure", "caracteristique_critique": "Absence éclats",
             "mode_defaillance": "Éclats bordure", "effets_defaillance": "Risque blessure",
             "G": 8, "causes_defaillance": "Sciage agressif", "O": 3,
             "controles_existants": "Inspection x50 100%", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Vitesse sciage réduite + chanfrein",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "06", "famille": "tracabilite",
             "fonction_exigence": "Identification", "caracteristique_critique": "Référence + lot",
             "mode_defaillance": "Confusion référence", "effets_defaillance": "Mauvais produit livré",
             "G": 8, "causes_defaillance": "Étiquetage défaillant", "O": 2,
             "controles_existants": "Scan code-barres", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Kanban physique", "responsable": "Resp. Qualité", "delai": "J+7"},
        ],
        "amdec_process": [
            {"no": "01", "operation_process": "OP-10 Sciage diamant", "etape_poste": "Scie diamant",
             "mode_defaillance": "Éclats sciage", "effets_produit": "Microfissures",
             "G": 8, "causes_process": "Vitesse élevée", "O": 4,
             "controles_process": "Inspection x50 100%", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Réduire vitesse, arrosage", "responsable": "Resp. Process",
             "delai": "J+15", "parametre_cle": "Vitesse", "valeur_cible": "1500 RPM"},
            {"no": "02", "operation_process": "OP-20 Rectification", "etape_poste": "Rectifieuse",
             "mode_defaillance": "Diamètre HT", "effets_produit": "Rebut",
             "G": 9, "causes_process": "Usure meule", "O": 3,
             "controles_process": "Pied à coulisse 100%", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Dressage meule 200 pcs", "responsable": "Resp. Process",
             "delai": "J+15", "parametre_cle": "Avance", "valeur_cible": "0.02 mm/pass"},
            {"no": "03", "operation_process": "OP-30 Polissage fin", "etape_poste": "Polisseuse",
             "mode_defaillance": "Ra > 50nm", "effets_produit": "Aspect terne",
             "G": 6, "causes_process": "Pâte usée", "O": 4,
             "controles_process": "Rugosimètre", "D": 3,
             "classe_criticite": "Surveillance",
             "actions_correctives": "Renouvellement pâte", "responsable": "Resp. Process",
             "delai": "J+30", "parametre_cle": "Durée polissage", "valeur_cible": "30 min"},
            {"no": "04", "operation_process": "OP-90 Contrôle final", "etape_poste": "Table qualité",
             "mode_defaillance": "Défaut non détecté", "effets_produit": "Livraison non-conforme",
             "G": 9, "causes_process": "Fatigue opérateur", "O": 3,
             "controles_process": "Inspection 100%", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Référentiels visuels", "responsable": "Resp. Qualité",
             "delai": "J+15", "parametre_cle": "Tous critères", "valeur_cible": "Conforme"},
        ],
        "gamme": [
            {"no_op": "10", "designation": "Réception matière brute",
             "description_detaillee": "Contrôle plaquettes minérales entrantes",
             "poste_machine": "Zone réception", "outillage_fixture": "Pied à coulisse",
             "parametre_1": "Épaisseur", "valeur_1": "2.3mm ± 0.05",
             "parametre_2": "Aspect", "valeur_2": "Sans défaut",
             "parametre_3": "—", "temps_min": 8,
             "point_controle": "Cotes + aspect", "moyen_controle": "Pied à coulisse + visuel",
             "frequence": "100%", "critere_acceptation": "Conforme certificat",
             "ref_dit": "DIT-010", "ref_infor": "OP-10"},
            {"no_op": "20", "designation": "Sciage diamant",
             "description_detaillee": "Découpe ronde Ø36mm",
             "poste_machine": "Scie diamant", "outillage_fixture": "Lame diamant",
             "parametre_1": "Vitesse rotation", "valeur_1": "1500 RPM",
             "parametre_2": "Avance", "valeur_2": "0.7 mm/min",
             "parametre_3": "Arrosage", "temps_min": 12,
             "point_controle": "Bordure", "moyen_controle": "Inspection x50",
             "frequence": "100%", "critere_acceptation": "0 éclat > 0.05mm",
             "ref_dit": "DIT-020", "ref_infor": "OP-20"},
            {"no_op": "30", "designation": "Rectification diamètre",
             "description_detaillee": "Mise à la cote Ø36mm ± 0.05",
             "poste_machine": "Rectifieuse cylindrique", "outillage_fixture": "Meule diamant",
             "parametre_1": "Diamètre cible", "valeur_1": "Ø36.00 ± 0.05",
             "parametre_2": "Avance", "valeur_2": "0.02mm/pass",
             "parametre_3": "—", "temps_min": 18,
             "point_controle": "Diamètre", "moyen_controle": "Pied à coulisse",
             "frequence": "100%", "critere_acceptation": "Ø36 ± 0.05",
             "ref_dit": "DIT-030", "ref_infor": "OP-30"},
            {"no_op": "40", "designation": "Polissage fin 2 faces",
             "description_detaillee": "Polissage fin double face pour Ra ≤ 50nm",
             "poste_machine": "Polisseuse double face", "outillage_fixture": "Pâte alumine 5µm",
             "parametre_1": "Durée polissage", "valeur_1": "30 min",
             "parametre_2": "Pression", "valeur_2": "1.0 bar",
             "parametre_3": "—", "temps_min": 35,
             "point_controle": "Rugosité Ra", "moyen_controle": "Rugosimètre",
             "frequence": "1/lot", "critere_acceptation": "Ra ≤ 50nm",
             "ref_dit": "DIT-040", "ref_infor": "OP-40"},
            {"no_op": "50", "designation": "Chanfrein bordure",
             "description_detaillee": "Chanfrein 0.1×45° périphérie",
             "poste_machine": "Chanfreineuse", "outillage_fixture": "Outil diamant",
             "parametre_1": "Angle", "valeur_1": "45°",
             "parametre_2": "Profondeur", "valeur_2": "0.1mm",
             "parametre_3": "—", "temps_min": 8,
             "point_controle": "Chanfrein", "moyen_controle": "Projecteur de profil",
             "frequence": "100%", "critere_acceptation": "Conforme",
             "ref_dit": "DIT-050", "ref_infor": "OP-50"},
            {"no_op": "60", "designation": "Contrôle final",
             "description_detaillee": "Contrôle dimensionnel + aspect",
             "poste_machine": "Métrologie", "outillage_fixture": "Métrologie complète",
             "parametre_1": "Diamètre", "valeur_1": "Ø36 ± 0.05",
             "parametre_2": "Épaisseur", "valeur_2": "2.0 ± 0.03",
             "parametre_3": "Aspect", "temps_min": 12,
             "point_controle": "Toutes cotes", "moyen_controle": "Métrologie",
             "frequence": "100%", "critere_acceptation": "Toutes cotes conformes",
             "ref_dit": "DIT-060", "ref_infor": "OP-60"},
            {"no_op": "70", "designation": "Conditionnement",
             "description_detaillee": "Emballage film ESD",
             "poste_machine": "Poste emballage", "outillage_fixture": "Film ESD",
             "parametre_1": "Type", "valeur_1": "ESD",
             "parametre_2": "Étiquette", "valeur_2": "REF + LOT + DATE",
             "parametre_3": "—", "temps_min": 6,
             "point_controle": "Étiquetage", "moyen_controle": "Scan",
             "frequence": "100%", "critere_acceptation": "Correct",
             "ref_dit": "DIT-070", "ref_infor": "OP-70"},
        ],
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# RÉFÉRENCES CÉRAMIQUE
# ═══════════════════════════════════════════════════════════════════════════════

CERAMIQUE_REFS = [
    {
        "code": "REF-CEBA-010",
        "designation": "Bague alumine 99% Ø10mm — rectification + polissage miroir",
        "type_produit": "bague",
        "matiere": "alumine_99",
        "traitements": ["rectif_diamant", "polissage_miroir"],
        "dimensions": {"diametre_mm": 10.0, "tolerance_diametre_mm": 0.02,
                       "epaisseur_mm": 3.0, "tolerance_epaisseur_mm": 0.02},
        "amdec_produit": [
            {"no": "01", "famille": "structurel",
             "fonction_exigence": "Densité matière", "caracteristique_critique": "Densité après frittage",
             "mode_defaillance": "Densité < 3.95 g/cm³",
             "effets_defaillance": "Porosité résiduelle, fragilité mécanique",
             "G": 9, "causes_defaillance": "Frittage incomplet, profil thermique incorrect",
             "O": 3, "controles_existants": "Mesure densité Archimède 1/lot",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Profil frittage validé + SPC densité",
             "responsable": "Resp. Process", "delai": "J+15"},
            {"no": "02", "famille": "structurel",
             "fonction_exigence": "Dureté", "caracteristique_critique": "Dureté Vickers HV",
             "mode_defaillance": "HV < 1700 (alumine 99% standard)",
             "effets_defaillance": "Usure prématurée en service",
             "G": 7, "causes_defaillance": "Microstructure non optimale, taille grain",
             "O": 3, "controles_existants": "Mesure dureté Vickers 1/lot",
             "D": 3, "classe_criticite": "Surveillance",
             "actions_correctives": "Validation taille grain par MEB, contrôle SPC",
             "responsable": "Resp. Qualité", "delai": "J+30"},
            {"no": "03", "famille": "structurel",
             "fonction_exigence": "Intégrité", "caracteristique_critique": "Absence microfissures",
             "mode_defaillance": "Microfissures internes",
             "effets_defaillance": "Casse en service sous charge",
             "G": 10, "causes_defaillance": "Choc thermique au refroidissement, défaut compaction",
             "O": 2, "controles_existants": "Contrôle ultrasons 100% + ressuage",
             "D": 4, "classe_criticite": "Action corrective",
             "actions_correctives": "Profil refroidissement contrôlé, contrôle US 100%",
             "responsable": "Resp. Qualité", "delai": "J+15"},
            {"no": "04", "famille": "geometrique",
             "fonction_exigence": "Conformité dimensionnelle", "caracteristique_critique": "Diamètre",
             "mode_defaillance": "Diamètre hors tolérance ± 0.02mm",
             "effets_defaillance": "Impossibilité montage assemblage",
             "G": 9, "causes_defaillance": "Retrait frittage non maîtrisé, rectif incorrecte",
             "O": 3, "controles_existants": "Mesure micromètre 100%",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "SPC retrait + dressage meule diamant 200 pcs",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "05", "famille": "structurel",
             "fonction_exigence": "Porosité", "caracteristique_critique": "Porosité ouverte",
             "mode_defaillance": "Porosité ouverte > 0.1%",
             "effets_defaillance": "Infiltration liquide, contamination",
             "G": 8, "causes_defaillance": "Frittage incomplet, atmosphère non contrôlée",
             "O": 3, "controles_existants": "Mesure porosité Archimède",
             "D": 3, "classe_criticite": "Surveillance",
             "actions_correctives": "Atmosphère frittage contrôlée O2/N2",
             "responsable": "Resp. Process", "delai": "J+30"},
            {"no": "06", "famille": "geometrique",
             "fonction_exigence": "État de surface", "caracteristique_critique": "Rugosité Ra",
             "mode_defaillance": "Ra > 10nm (polissage miroir non atteint)",
             "effets_defaillance": "Aspect non-conforme, frottement excessif",
             "G": 6, "causes_defaillance": "Polissage diamant insuffisant",
             "O": 4, "controles_existants": "Rugosimètre 1/lot",
             "D": 3, "classe_criticite": "Surveillance",
             "actions_correctives": "Standard durée polissage diamant",
             "responsable": "Resp. Process", "delai": "J+30"},
            {"no": "07", "famille": "tracabilite",
             "fonction_exigence": "Identification lot", "caracteristique_critique": "Traçabilité fonderie",
             "mode_defaillance": "Perte traçabilité lot poudre",
             "effets_defaillance": "Impossibilité de remonter à la cause en cas défaut",
             "G": 7, "causes_defaillance": "Documentation incomplète",
             "O": 3, "controles_existants": "Numérotation lots + dossier ERP",
             "D": 2, "classe_criticite": "Surveillance",
             "actions_correctives": "Digitalisation dossier traçabilité poudre→produit",
             "responsable": "Resp. Qualité", "delai": "J+45"},
        ],
        "amdec_process": [
            {"no": "01", "operation_process": "OP-10 Pressage isostatique",
             "etape_poste": "Presse isostatique CIP",
             "mode_defaillance": "Compaction inégale",
             "effets_produit": "Densité hétérogène après frittage",
             "G": 8, "causes_process": "Pression non homogène, poudre humide",
             "O": 3, "controles_process": "Pesée + mesure densité cru",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Contrôle humidité poudre < 0.5%, pression validée",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Pression CIP", "valeur_cible": "200 MPa ± 10"},
            {"no": "02", "operation_process": "OP-20 Frittage",
             "etape_poste": "Four haute température 1650°C",
             "mode_defaillance": "Profil thermique non conforme",
             "effets_produit": "Densité finale insuffisante",
             "G": 9, "causes_process": "Dérive thermocouples, panne résistances",
             "O": 2, "controles_process": "Enregistrement profil thermique 100%",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Étalonnage thermocouples mensuel, alarme dérive",
             "responsable": "Maintenance", "delai": "J+15",
             "parametre_cle": "Température palier", "valeur_cible": "1650°C ± 10"},
            {"no": "03", "operation_process": "OP-30 Rectification diamant",
             "etape_poste": "Rectifieuse CN diamant",
             "mode_defaillance": "Cote diamètre hors tolérance",
             "effets_produit": "Pièce hors spec",
             "G": 9, "causes_process": "Usure meule diamant",
             "O": 3, "controles_process": "Mesure micromètre 100%",
             "D": 2, "classe_criticite": "Action corrective",
             "actions_correctives": "Dressage meule 200 pcs",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Avance meule", "valeur_cible": "0.005 mm/pass"},
            {"no": "04", "operation_process": "OP-50 Contrôle densité",
             "etape_poste": "Laboratoire",
             "mode_defaillance": "Mesure densité erronée",
             "effets_produit": "Lots non-conformes acceptés",
             "G": 9, "causes_process": "Balance déréglée, eau distillée contaminée",
             "O": 2, "controles_process": "Étalonnage balance hebdo + témoin densité",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Procédure étalonnage strict, échantillon témoin",
             "responsable": "Resp. Qualité", "delai": "J+30",
             "parametre_cle": "Densité Archimède", "valeur_cible": "≥ 3.95 g/cm³"},
            {"no": "05", "operation_process": "OP-90 Contrôle final",
             "etape_poste": "Table qualité",
             "mode_defaillance": "Défaut non détecté",
             "effets_produit": "Livraison pièce non-conforme",
             "G": 9, "causes_process": "Fatigue opérateur",
             "O": 3, "controles_process": "Inspection 100%",
             "D": 3, "classe_criticite": "Action corrective",
             "actions_correctives": "Référentiels visuels, rotation 2h",
             "responsable": "Resp. Qualité", "delai": "J+15",
             "parametre_cle": "Tous critères", "valeur_cible": "Conforme"},
        ],
        "gamme": [
            {"no_op": "10", "designation": "Préparation poudre alumine",
             "description_detaillee": "Pesée et mélange poudre alumine 99% + liant",
             "poste_machine": "Mélangeur planétaire", "outillage_fixture": "Bol acier inox",
             "parametre_1": "Quantité poudre", "valeur_1": "Selon recette",
             "parametre_2": "Liant", "valeur_2": "PVA 2% massique",
             "parametre_3": "Durée mélange", "temps_min": 30,
             "point_controle": "Homogénéité", "moyen_controle": "Visuel + densité apparente",
             "frequence": "100%", "critere_acceptation": "Densité apparente conforme",
             "ref_dit": "DIT-010", "ref_infor": "OP-10"},
            {"no_op": "20", "designation": "Pressage isostatique CIP",
             "description_detaillee": "Compactage à froid sous pression isostatique",
             "poste_machine": "Presse CIP", "outillage_fixture": "Moule élastomère",
             "parametre_1": "Pression", "valeur_1": "200 MPa ± 10",
             "parametre_2": "Durée maintien", "valeur_2": "60s",
             "parametre_3": "—", "temps_min": 15,
             "point_controle": "Densité cru", "moyen_controle": "Pesée + mesure",
             "frequence": "100%", "critere_acceptation": "Densité cru ≥ 60% théorique",
             "ref_dit": "DIT-020", "ref_infor": "OP-20"},
            {"no_op": "30", "designation": "Déliantage",
             "description_detaillee": "Élimination liant organique en four bas T° (500°C)",
             "poste_machine": "Four déliantage", "outillage_fixture": "Plaques céramique",
             "parametre_1": "Température max", "valeur_1": "500°C",
             "parametre_2": "Vitesse montée", "valeur_2": "1°C/min",
             "parametre_3": "Atmosphère", "temps_min": 720,
             "point_controle": "Perte masse", "moyen_controle": "Pesée avant/après",
             "frequence": "100%", "critere_acceptation": "Perte 2% ± 0.2",
             "ref_dit": "DIT-030", "ref_infor": "OP-30"},
            {"no_op": "40", "designation": "Frittage haute température",
             "description_detaillee": "Frittage final 1650°C atmosphère contrôlée",
             "poste_machine": "Four frittage 1700°C max", "outillage_fixture": "Plateaux alumine",
             "parametre_1": "Température palier", "valeur_1": "1650°C ± 10",
             "parametre_2": "Durée palier", "valeur_2": "120 min",
             "parametre_3": "Atmosphère", "temps_min": 480,
             "point_controle": "Profil thermique", "moyen_controle": "Enregistreur thermo",
             "frequence": "100%", "critere_acceptation": "Profil conforme spec",
             "ref_dit": "DIT-040", "ref_infor": "OP-40"},
            {"no_op": "50", "designation": "Contrôle densité Archimède",
             "description_detaillee": "Mesure densité par poussée d'Archimède",
             "poste_machine": "Balance Archimède 0.001g", "outillage_fixture": "Bain eau distillée",
             "parametre_1": "Densité", "valeur_1": "≥ 3.95 g/cm³",
             "parametre_2": "Porosité ouverte", "valeur_2": "≤ 0.1%",
             "parametre_3": "—", "temps_min": 15,
             "point_controle": "Densité + porosité", "moyen_controle": "Archimède",
             "frequence": "1/lot", "critere_acceptation": "Conforme spec ISO 17561",
             "ref_dit": "DIT-050", "ref_infor": "OP-50"},
            {"no_op": "60", "designation": "Rectification diamant Ø",
             "description_detaillee": "Rectification cylindrique au diamètre Ø10mm",
             "poste_machine": "Rectifieuse CN diamant", "outillage_fixture": "Meule diamant grain 80",
             "parametre_1": "Diamètre cible", "valeur_1": "Ø10.00 ± 0.02",
             "parametre_2": "Avance", "valeur_2": "0.005 mm/pass",
             "parametre_3": "—", "temps_min": 25,
             "point_controle": "Diamètre", "moyen_controle": "Micromètre 0.001mm",
             "frequence": "100%", "critere_acceptation": "Ø10 ± 0.02",
             "ref_dit": "DIT-060", "ref_infor": "OP-60"},
            {"no_op": "70", "designation": "Polissage miroir diamant",
             "description_detaillee": "Polissage final pâte diamant 1µm pour Ra ≤ 10nm",
             "poste_machine": "Polisseuse rotative", "outillage_fixture": "Pâte diamant 1µm",
             "parametre_1": "Durée polissage", "valeur_1": "30 min",
             "parametre_2": "Pression", "valeur_2": "1 bar",
             "parametre_3": "—", "temps_min": 35,
             "point_controle": "Rugosité Ra", "moyen_controle": "Rugosimètre",
             "frequence": "1/lot", "critere_acceptation": "Ra ≤ 10nm",
             "ref_dit": "DIT-070", "ref_infor": "OP-70"},
            {"no_op": "80", "designation": "Contrôle dureté Vickers",
             "description_detaillee": "Mesure dureté Vickers HV1 sur échantillon",
             "poste_machine": "Microduromètre Vickers", "outillage_fixture": "Indenteur diamant",
             "parametre_1": "Charge", "valeur_1": "1 kgf",
             "parametre_2": "Durée", "valeur_2": "10s",
             "parametre_3": "—", "temps_min": 10,
             "point_controle": "Dureté HV", "moyen_controle": "Microduromètre",
             "frequence": "1/lot", "critere_acceptation": "HV ≥ 1700",
             "ref_dit": "DIT-080", "ref_infor": "OP-80"},
            {"no_op": "90", "designation": "Contrôle final + libération",
             "description_detaillee": "Contrôle dimensionnel + aspect + libération lot",
             "poste_machine": "Métrologie", "outillage_fixture": "Métrologie complète",
             "parametre_1": "Diamètre", "valeur_1": "Ø10 ± 0.02",
             "parametre_2": "Hauteur", "valeur_2": "3 ± 0.02",
             "parametre_3": "Aspect", "temps_min": 15,
             "point_controle": "Toutes cotes + aspect", "moyen_controle": "Métrologie + visuel x50",
             "frequence": "100%", "critere_acceptation": "Toutes cotes conformes",
             "ref_dit": "DIT-090", "ref_infor": "OP-90"},
            {"no_op": "100", "designation": "Conditionnement",
             "description_detaillee": "Emballage individuel boîte rigide",
             "poste_machine": "Poste emballage", "outillage_fixture": "Boîte rigide individuelle",
             "parametre_1": "Type", "valeur_1": "Boîte rigide + mousse",
             "parametre_2": "Étiquette", "valeur_2": "REF + LOT + DATE",
             "parametre_3": "—", "temps_min": 8,
             "point_controle": "Étiquetage", "moyen_controle": "Scan",
             "frequence": "100%", "critere_acceptation": "Correct",
             "ref_dit": "DIT-100", "ref_infor": "OP-100"},
        ],
    },
    {
        "code": "REF-CECZ-005",
        "designation": "Cale zircone Y-TZP 5×5×1mm — rectification diamant",
        "type_produit": "cale",
        "matiere": "zircone_y_tzp",
        "traitements": ["rectif_diamant"],
        "dimensions": {"diametre_mm": 5.0, "tolerance_diametre_mm": 0.01,
                       "epaisseur_mm": 1.0, "tolerance_epaisseur_mm": 0.01},
        "amdec_produit": [
            {"no": "01", "famille": "structurel",
             "fonction_exigence": "Densité matière", "caracteristique_critique": "Densité après frittage",
             "mode_defaillance": "Densité < 6.05 g/cm³",
             "effets_defaillance": "Porosité résiduelle, fragilité",
             "G": 9, "causes_defaillance": "Frittage incomplet", "O": 3,
             "controles_existants": "Densité Archimède 1/lot", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Profil frittage validé",
             "responsable": "Resp. Process", "delai": "J+15"},
            {"no": "02", "famille": "structurel",
             "fonction_exigence": "Stabilité phase Y-TZP", "caracteristique_critique": "Phase quadratique",
             "mode_defaillance": "Transformation t→m sous charge (vieillissement)",
             "effets_defaillance": "Microfissures, perte propriétés mécaniques",
             "G": 9, "causes_defaillance": "Stabilisation Y2O3 insuffisante",
             "O": 2, "controles_existants": "Diffraction X périodique",
             "D": 4, "classe_criticite": "Action corrective",
             "actions_correctives": "Spec Y2O3 3 mol% strict, contrôle DRX trimestriel",
             "responsable": "Resp. Qualité", "delai": "J+30"},
            {"no": "03", "famille": "geometrique",
             "fonction_exigence": "Cotes principales", "caracteristique_critique": "5×5mm + épaisseur 1mm",
             "mode_defaillance": "Cotes hors tolérance ± 0.01mm",
             "effets_defaillance": "Cale inutilisable", "G": 9,
             "causes_defaillance": "Rectif incorrecte", "O": 3,
             "controles_existants": "Micromètre 100%", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "SPC dimensions, dressage meule diamant 200 pcs",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "04", "famille": "geometrique",
             "fonction_exigence": "Parallélisme faces", "caracteristique_critique": "Parallélisme",
             "mode_defaillance": "Défaut parallélisme > 0.005mm",
             "effets_defaillance": "Cale inefficace, jeu variable",
             "G": 8, "causes_defaillance": "Bridage rectif incorrect",
             "O": 3, "controles_existants": "Comparateur sur marbre", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Bridage par 3 points calibré",
             "responsable": "BT Qualité", "delai": "J+15"},
            {"no": "05", "famille": "structurel",
             "fonction_exigence": "Intégrité", "caracteristique_critique": "Absence éclats angles",
             "mode_defaillance": "Éclats sur arêtes vives",
             "effets_defaillance": "Aspect non-conforme, risque blessure",
             "G": 7, "causes_defaillance": "Manutention brutale, rectif sans chanfrein",
             "O": 4, "controles_existants": "Inspection x50 100%", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Chanfrein 0.05mm + manutention pince adaptée",
             "responsable": "Resp. Process", "delai": "J+15"},
            {"no": "06", "famille": "tracabilite",
             "fonction_exigence": "Identification lot", "caracteristique_critique": "Traçabilité",
             "mode_defaillance": "Perte traçabilité lot",
             "effets_defaillance": "Impossibilité de remonter cause défaut",
             "G": 7, "causes_defaillance": "Documentation incomplète",
             "O": 3, "controles_existants": "Numérotation lot + dossier", "D": 2,
             "classe_criticite": "Surveillance",
             "actions_correctives": "Digitalisation dossier",
             "responsable": "Resp. Qualité", "delai": "J+45"},
        ],
        "amdec_process": [
            {"no": "01", "operation_process": "OP-10 Pressage CIP", "etape_poste": "Presse CIP",
             "mode_defaillance": "Compaction inégale", "effets_produit": "Densité hétérogène",
             "G": 8, "causes_process": "Pression non homogène", "O": 3,
             "controles_process": "Densité cru", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Pression validée 200 MPa", "responsable": "Resp. Process",
             "delai": "J+15", "parametre_cle": "Pression", "valeur_cible": "200 MPa"},
            {"no": "02", "operation_process": "OP-20 Frittage Y-TZP", "etape_poste": "Four 1500°C",
             "mode_defaillance": "Profil thermique HC", "effets_produit": "Phase non stabilisée",
             "G": 10, "causes_process": "Thermocouples dérivés", "O": 2,
             "controles_process": "Enregistrement profil 100%", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Étalonnage thermo mensuel",
             "responsable": "Maintenance", "delai": "J+15",
             "parametre_cle": "Température palier", "valeur_cible": "1500°C ± 10"},
            {"no": "03", "operation_process": "OP-30 Rectification 6 faces",
             "etape_poste": "Rectif diamant CN",
             "mode_defaillance": "Cotes ou parallélisme HT",
             "effets_produit": "Cale inutilisable", "G": 9,
             "causes_process": "Usure meule, bridage incorrect", "O": 3,
             "controles_process": "Métrologie 100%", "D": 2,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Dressage meule + bridage 3 points",
             "responsable": "Resp. Process", "delai": "J+15",
             "parametre_cle": "Avance meule", "valeur_cible": "0.003 mm/pass"},
            {"no": "04", "operation_process": "OP-50 Contrôle DRX",
             "etape_poste": "Laboratoire DRX",
             "mode_defaillance": "Phase mesurée incorrecte",
             "effets_produit": "Lots non stabilisés acceptés",
             "G": 9, "causes_process": "Étalonnage DRX décalé", "O": 2,
             "controles_process": "Échantillon témoin DRX", "D": 4,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Étalonnage DRX trimestriel",
             "responsable": "Resp. Qualité", "delai": "J+30",
             "parametre_cle": "% phase quadratique", "valeur_cible": "≥ 95%"},
            {"no": "05", "operation_process": "OP-90 Contrôle final",
             "etape_poste": "Table qualité",
             "mode_defaillance": "Défaut non détecté",
             "effets_produit": "Livraison non-conforme", "G": 9,
             "causes_process": "Fatigue opérateur", "O": 3,
             "controles_process": "Inspection 100%", "D": 3,
             "classe_criticite": "Action corrective",
             "actions_correctives": "Référentiels visuels",
             "responsable": "Resp. Qualité", "delai": "J+15",
             "parametre_cle": "Tous critères", "valeur_cible": "Conforme"},
        ],
        "gamme": [
            {"no_op": "10", "designation": "Préparation poudre Y-TZP",
             "description_detaillee": "Mélange zircone stabilisée 3% Y2O3 + liant",
             "poste_machine": "Mélangeur planétaire", "outillage_fixture": "Bol inox",
             "parametre_1": "Quantité poudre", "valeur_1": "Selon recette",
             "parametre_2": "Y2O3", "valeur_2": "3 mol%",
             "parametre_3": "Liant PVA", "temps_min": 30,
             "point_controle": "Homogénéité", "moyen_controle": "Visuel + densité",
             "frequence": "100%", "critere_acceptation": "Densité apparente conforme",
             "ref_dit": "DIT-010", "ref_infor": "OP-10"},
            {"no_op": "20", "designation": "Pressage CIP",
             "description_detaillee": "Compactage isostatique à froid",
             "poste_machine": "Presse CIP", "outillage_fixture": "Moule élastomère cale",
             "parametre_1": "Pression", "valeur_1": "200 MPa ± 10",
             "parametre_2": "Durée", "valeur_2": "60s",
             "parametre_3": "—", "temps_min": 12,
             "point_controle": "Densité cru", "moyen_controle": "Pesée + mesure",
             "frequence": "100%", "critere_acceptation": "Densité cru ≥ 60%",
             "ref_dit": "DIT-020", "ref_infor": "OP-20"},
            {"no_op": "30", "designation": "Déliantage",
             "description_detaillee": "Élimination liant à 500°C",
             "poste_machine": "Four déliantage", "outillage_fixture": "Plaques céramique",
             "parametre_1": "Température", "valeur_1": "500°C",
             "parametre_2": "Vitesse montée", "valeur_2": "1°C/min",
             "parametre_3": "—", "temps_min": 600,
             "point_controle": "Perte masse", "moyen_controle": "Pesée",
             "frequence": "100%", "critere_acceptation": "Perte 2% ± 0.2",
             "ref_dit": "DIT-030", "ref_infor": "OP-30"},
            {"no_op": "40", "designation": "Frittage Y-TZP",
             "description_detaillee": "Frittage 1500°C atmosphère air",
             "poste_machine": "Four frittage 1600°C max", "outillage_fixture": "Plateaux alumine",
             "parametre_1": "Température palier", "valeur_1": "1500°C ± 10",
             "parametre_2": "Durée palier", "valeur_2": "120 min",
             "parametre_3": "Atmosphère", "temps_min": 360,
             "point_controle": "Profil thermique", "moyen_controle": "Enregistreur",
             "frequence": "100%", "critere_acceptation": "Profil conforme",
             "ref_dit": "DIT-040", "ref_infor": "OP-40"},
            {"no_op": "50", "designation": "Contrôle densité + DRX",
             "description_detaillee": "Densité Archimède + diffraction X (% phase t)",
             "poste_machine": "Lab densité + DRX", "outillage_fixture": "Balance + diffractomètre",
             "parametre_1": "Densité", "valeur_1": "≥ 6.05 g/cm³",
             "parametre_2": "Phase quadratique", "valeur_2": "≥ 95%",
             "parametre_3": "—", "temps_min": 30,
             "point_controle": "Densité + phase", "moyen_controle": "Archimède + DRX",
             "frequence": "1/lot", "critere_acceptation": "Conforme spec",
             "ref_dit": "DIT-050", "ref_infor": "OP-50"},
            {"no_op": "60", "designation": "Rectification 6 faces diamant",
             "description_detaillee": "Rectification 6 faces aux cotes finales",
             "poste_machine": "Rectif CN diamant 6 faces", "outillage_fixture": "Meule diamant + bridage 3 points",
             "parametre_1": "Cotes 5×5×1", "valeur_1": "5.00 × 5.00 × 1.00 ± 0.01",
             "parametre_2": "Avance", "valeur_2": "0.003 mm/pass",
             "parametre_3": "—", "temps_min": 30,
             "point_controle": "Cotes + parallélisme", "moyen_controle": "Micromètre + comparateur",
             "frequence": "100%", "critere_acceptation": "Cotes ± 0.01, parallélisme ≤ 0.005",
             "ref_dit": "DIT-060", "ref_infor": "OP-60"},
            {"no_op": "70", "designation": "Chanfrein arêtes",
             "description_detaillee": "Chanfrein 0.05mm sur 12 arêtes",
             "poste_machine": "Tribofinisseur", "outillage_fixture": "Médias céramique",
             "parametre_1": "Durée", "valeur_1": "60 min",
             "parametre_2": "Médias", "valeur_2": "Céramique 3mm",
             "parametre_3": "—", "temps_min": 65,
             "point_controle": "Chanfrein arêtes", "moyen_controle": "Inspection x20",
             "frequence": "100%", "critere_acceptation": "Toutes arêtes chanfreinées",
             "ref_dit": "DIT-070", "ref_infor": "OP-70"},
            {"no_op": "80", "designation": "Contrôle final",
             "description_detaillee": "Métrologie complète + aspect",
             "poste_machine": "Métrologie", "outillage_fixture": "Métrologie + microscope",
             "parametre_1": "Cotes", "valeur_1": "5×5×1 ± 0.01",
             "parametre_2": "Parallélisme", "valeur_2": "≤ 0.005",
             "parametre_3": "Aspect", "temps_min": 12,
             "point_controle": "Toutes cotes + aspect", "moyen_controle": "Métrologie",
             "frequence": "100%", "critere_acceptation": "Toutes cotes conformes",
             "ref_dit": "DIT-080", "ref_infor": "OP-80"},
            {"no_op": "90", "designation": "Conditionnement",
             "description_detaillee": "Emballage compartimenté + étiquetage",
             "poste_machine": "Poste emballage", "outillage_fixture": "Plateau compartimenté",
             "parametre_1": "Type", "valeur_1": "Plateau alvéolé + film",
             "parametre_2": "Étiquette", "valeur_2": "REF + LOT + DATE + QTE",
             "parametre_3": "—", "temps_min": 8,
             "point_controle": "Étiquetage", "moyen_controle": "Scan",
             "frequence": "100%", "critere_acceptation": "Correct",
             "ref_dit": "DIT-090", "ref_infor": "OP-90"},
        ],
    },
]


# ═══════════════════════════════════════════════════════════════════════════════
# FONCTION DE CRÉATION
# ═══════════════════════════════════════════════════════════════════════════════

def creer_reference(spec, categorie_code):
    code = spec["code"]
    designation = spec["designation"]
    cat_dir = CATEGORIES / categorie_code
    ref_dir = cat_dir / "references" / code
    data_dir = ref_dir / "data"
    ref_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(exist_ok=True)

    metadata = {
        "reference": code,
        "categorie": categorie_code,
        "designation": designation,
        "type_produit": spec["type_produit"],
        "matiere": spec["matiere"],
        "traitements": spec["traitements"],
        "dimensions": spec["dimensions"],
        "documents": {
            "AMDEC_produit": "data/amdec_produit.json",
            "AMDEC_process": "data/amdec_process.json",
            "gamme": "data/gamme.json",
        },
        "infor_reference": None,
        "date_creation": date.today().isoformat(),
        "statut": "valide",
        "redige_par": "Bureau Technique",
        "approuve_par": None,
        "indice_revision": "A",
    }
    (ref_dir / "metadata.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    (data_dir / "amdec_produit.json").write_text(
        json.dumps({"reference": code, "document": "AMDEC Produit",
                    "designation": designation,
                    "modes_defaillance": spec["amdec_produit"]},
                   ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (data_dir / "amdec_process.json").write_text(
        json.dumps({"reference": code, "document": "AMDEC Process",
                    "designation": designation,
                    "modes_defaillance": spec["amdec_process"]},
                   ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (data_dir / "gamme.json").write_text(
        json.dumps({"reference": code, "document": "Gamme de Production",
                    "designation": designation,
                    "operations": spec["gamme"]},
                   ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return code, len(spec["amdec_produit"]), len(spec["amdec_process"]), len(spec["gamme"])


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    print("=== Categorie : Glace nue ===")
    for spec in GLACE_NUE_REFS:
        code, np_, npr, no_ = creer_reference(spec, "glace_nue")
        print(f"  [OK] {code} : {np_} modes produit | {npr} modes process | {no_} operations")

    print("\n=== Categorie : Ceramique ===")
    for spec in CERAMIQUE_REFS:
        code, np_, npr, no_ = creer_reference(spec, "ceramique")
        print(f"  [OK] {code} : {np_} modes produit | {npr} modes process | {no_} operations")

    print(f"\nTotal : {len(GLACE_NUE_REFS) + len(CERAMIQUE_REFS)} references creees.")
